services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARTIFACTORY: ${ARTIFACTORY}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    env_file:
      - .env
    volumes:
      - .:/app
    command: php example.php
